#Modified on Tue Jul 21 20:37:32 IST 2026
#Tue Jul 21 20:37:32 IST 2026
database.driver=oracle.jdbc.driver.OracleDriver
database.password=Eh436W3fzed2OmLuymDi16Zt6hdkMNHDxqrANXagUsk\=
database.url=jdbc\:oracle\:thin\:@//localhost\:1521/FREEPDB1
database.username=sdmx_portal
encrypt.password=7df05ef4-2f32-412c-83ae-26c69138176c
encrypt.salt=8d3e9071-c1fe-481a-95e5-00ff8d40f3b5
http.request.useragent=FusionRegistry/${version}
security.auth.prov={"authType"\:"registry"}
security.password=$2a$10$uBoqd3.Dtv8m3RpMkOP1pe7DhpEznyV484.pG.B3hnHyEsYHLSPYq
security.username=admin
